/**
 * Creator — the only PII surface (db-architecture.md §5.1). Identity (email/
 * password) lives in **Better Auth**, linked via `authUserId`, NOT duplicated
 * here. The durable, non-PII `publisherKeyId` survives account deletion and
 * anchors repeat-infringer linkage on packs + verdicts.
 */

import { pgTable, text, timestamp, uuid } from 'drizzle-orm/pg-core';
import { accountRole, accountStatus } from './enums';

export const account = pgTable('account', {
  id: uuid('id').primaryKey().defaultRandom(),
  // FK → Better Auth `user.id` once auth lands. Nullable + no FK for now: Better
  // Auth's tables don't exist yet (generated by its CLI), and the official seed
  // account has no auth identity. Backfill + add NOT NULL/FK when auth lands.
  authUserId: text('auth_user_id').unique(),
  publisherKeyId: text('publisher_key_id').notNull().unique(),
  nickname: text('nickname').notNull(), // not unique — identity is id / publisher_key_id
  avatarEmoji: text('avatar_emoji'),
  role: accountRole('role').notNull().default('user'),
  status: accountStatus('status').notNull().default('active'),
  createdAt: timestamp('created_at', { withTimezone: true }).notNull().defaultNow(),
  updatedAt: timestamp('updated_at', { withTimezone: true }),
  deletedAt: timestamp('deleted_at', { withTimezone: true }), // set when PII is erased
});
