/**
 * Drizzle schema barrel — the full v2 app-domain model (db-architecture.md §5).
 * drizzle-kit reads this file (see drizzle.config.ts) and collects every exported
 * table + enum. Better Auth owns its own tables (`user`/`session`/`auth_account`/
 * `verification`), generated by its CLI when auth lands — NOT authored here;
 * `account.authUserId` links to them. Budget/rate counters live in Redis, never here.
 */

export * from './enums';
export * from './account';
export * from './published-pack';
export * from './language';
export * from './content-policy';
export * from './rating';
export * from './install';
export * from './report';
export * from './moderation-verdict';
